### ISSUE TITLE
how to create the hash string in windows

### ISSUE THREAD

**Issue by amey7** [Bruno-Furtado/react-native-sms-retriever#11]
### Environment

* React Native Version  "0.59.8",
* Platform: Android
* Device: Simulator
* OS Version
* react-native-sms-retriever version
* Devtools: Xcode Version / Android Studio Version
* Build Tools Version (Android only)

### Description

I am trying to run the example which is being given by your team in github.everything executes fine.but when i send sms through the emulator shortcut the alert returns undefined.i understand this may be the problem with hashstring as it is required.could you please help me out on how to create the required hash string in windows sommand prompt.because when i run the commands given by you in earlier issues theirs an error 'xxd' is not recognized as an internal or external command'.thank you

**Comment by Bruno-Furtado** [comment]
@amey7 please check [this documentation](https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string).
