### ISSUE TITLE
Doesn't seem to install correctly

### ISSUE THREAD

**Issue by RockinRonE** [Bruno-Furtado/react-native-sms-retriever#12]
### Environment

* "react-native": "0.59.5",
* Platform: Android
* Device: Pixel 3

* react-native-sms-retriever version: current
* Devtools: Android Studio Version: 3.1.2
* Build Tools Version (Android only)

Android Studio 3.1.2
Build #AI-173.4720617, built on April 13, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.14.5

### Description

I followed the installation directions. I am now seeing this error:

<img width="477" alt="Screen Shot 2019-06-19 at 4 29 24 PM" src="https://user-images.githubusercontent.com/8163241/59803075-0eb2a980-92b0-11e9-9cf8-c816ee0995c8.png">

**Comment by Bruno-Furtado** [comment]
@RockinRonE, can you describe the installations steps that you followed?

**Comment by Bruno-Furtado** [comment]
@RockinRonE, any feedback? I will close this issue, ok?
