### ISSUE TITLE
Support for AndroidX and React Native v0.60

### ISSUE THREAD

**Issue by Thronie** [Bruno-Furtado/react-native-sms-retriever#14]
Describe the Feature
Compatibility with React Native v0.60. Here is some breaking changes: https://facebook.github.io/react-native/blog/2019/07/03/version-60

Possible Implementations
Adapt the code, here a starting point https://react-native-community.github.io/upgrade-helper/

Related Issues
The current version of react-native-sms-retriever is not compatible with React Native v0.60

**Comment by malithjkmt** [comment]
**requestPhoneNumber**, **startSmsRetriever** works but, **addSmsListener** does not work on

```
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-sms-retriever": "^1.0.3",
```

@Bruno-Furtado  any plan on looking in to this soon?

**Comment by Bruno-Furtado** [comment]
@malithjkmt, yeah. I will look this week.

**Comment by Thronie** [comment]
@Bruno-Furtado What is the status?

**Comment by skptricks** [comment]
This is not working with react native version 0.60 and unable to detect sms using this library. please let me know what need to be done for this.

**Comment by arthurstockler** [comment]
Fala Bruno! Alguma posição sobre AndroidX ?

**Comment by QuanticPotatoes** [comment]
@Bruno-Furtado any update with react native 0.60 support ?

**Comment by Bruno-Furtado** [comment]
Hey guys, sorry about that.
I'm busy as a bee last weeks. 😕
Can anyone help me with this improvement?

**Comment by cmasus** [comment]
This react-native-sms-retriever works on RN 0.60 or higher if you use the Jetifier. I have proposed PR #16 to make this fully compatible with RN 0.60 and higher.

**Comment by ashu-11** [comment]
@Bruno-Furtado  any update regarding this method it is not reading the message from the apk

**Comment by Ericky14** [comment]
Any news on this? It doesn't seem to work even with @cmasus 's PR

**Comment by wagnerdelima** [comment]
The issue still persists. Any updates on this guys?

**Comment by Bruno-Furtado** [comment]
Hey guys,
I updated the RN version of the project to 0.61.5: https://github.com/Bruno-Furtado/react-native-sms-retriever/pull/22
Now the module supporting AndroidX and new versions of RN.
