### ISSUE TITLE
Null is not an object (evaluating RNSmsRetrieverModule.requestPhoneNumber

### ISSUE THREAD

**Issue by HodayaGruzman** [Bruno-Furtado/react-native-sms-retriever#15]
### Android

* React Native 0.60
* Platform: Android 
* Device: Which One / Simulator

### Description

I just add this plugin to my app using autolinking and when I running it, its crashed,

**Comment by skptricks** [comment]
This is not working and also listener not working when any sms received. Currently working on react native version 0.60.

**Comment by Bruno-Furtado** [comment]
Moving to https://github.com/Bruno-Furtado/react-native-sms-retriever/issues/14

**Comment by Kumar2106** [comment]
This issue is still existing. Right now i am working on react native project. When i am running through npm run android, it is working fine but when i am using expo start it is giving me the same issue, i don't know why this is happening.

**Comment by yusufboran** [comment]
I get this error. I'm not sure if the library works with expo

**Comment by anirudhj111** [comment]
Getting the same issue , when running with a expo managed project.
