### ISSUE TITLE
where to store hash key generated from keystore

### ISSUE THREAD

**Issue by sanchez1023** [Bruno-Furtado/react-native-sms-retriever#19]
### Environment

* React Native Version
* Platform: iOS / Android / Both
* Device: Which One / Simulator
* OS Version
* react-native-sms-retriever version
* Devtools: Xcode Version / Android Studio Version
* Build Tools Version (Android only)

### Description

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or prints if needed.

### Solution

Do you know what needs to be done to address this issue? Ideally, provide a pull request with a fix.

**Comment by Bruno-Furtado** [comment]
@sanchez1023, 

Take a look at [SMS Rules](https://github.com/Bruno-Furtado/react-native-sms-retriever/wiki/SMS-Rules) to know more about the hash key.

The latest version of the module (v1.1.0) includes the keystore inside the example folder so you can pull the latest changes (master branch) and try to read the message again using the same key as described on the SMS Rules page.
