### ISSUE TITLE
Only emits first event with redux-saga

### ISSUE THREAD

**Issue by NikitaNeganov** [Bruno-Furtado/react-native-sms-retriever#20]
### Environment

* React Native Version: 0.59.10
* Platform: iOS / Android / Both: Android, obviously
* Device: Which One / Simulator: Android Studio Simulator
* OS Version: Android 10
* react-native-sms-retriever version: 1.0.3
* Devtools: Xcode Version / Android Studio Version: 
Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 31, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
* Build Tools Version (Android only): 28.0.3

### Description

I'm using `redux-saga` `eventChannel` to subscribe to external events, like so
```js
import { eventChannel } from 'redux-saga';
import { take, call } from 'redux-saga/effects';
import SmsRetriever from 'react-native-sms-retriever';


function createOnOTPChannel() {
  return eventChannel((emit) => {
    SmsRetriever.addSmsListener((event) => {
      console.log('received event in channel');
      emit(event.message);
    });

    return () => {
      console.log('removing');
      SmsRetriever.removeSmsListener();
    };
  });
}

function* watchOTP() {
  const registered = yield SmsRetriever.startSmsRetriever();
  if (registered) {
    const otpChannel = yield call(createOnOTPChannel);
    while (true) {
      const payload = yield take(otpChannel);
      console.log(payload);
    }
  }
}

export default watchOTP;

```

While receiving SMS, `eventChannel` only receives and emits the first one, others just go unnoticed. I specifically logged `removing` to see if there's a problem with the saga, but it seems not.
### Update
Apparently, the listener itself is only capable of receiving single event, because the following code renders the same behavior:
```js
React.useEffect(() => {
    const effect = async () => {
      const registered = await SmsRetriever.startSmsRetriever();

      if (registered) {
        SmsRetriever.addSmsListener((event) => {
          console.log('received event in App.js');
          console.log(event.message);
        });
      }
    };

    effect();

    return SmsRetriever.removeSmsListener();
  }, []);
```

### Another update
This behavior is inconsistent. Since  I wanted to always have a listener attached, I made it recursive (`onEvent` function):
```js
const onEvent = (emit) => {
  SmsRetriever.addSmsListener((event) => {
    console.log('created');
    emit(event.message);
    SmsRetriever.removeSmsListener();
    console.log('removed');
    onEvent(emit);
  });

  return () => {
    SmsRetriever.removeSmsListener();
    console.log('removed from return');
  };
};

function createOnOTPChannel() {
  return eventChannel(onEvent);
}

function* watchOTP() {
  const registered = yield SmsRetriever.startSmsRetriever();

  if (registered) {
    const otpChannel = yield call(createOnOTPChannel);

    while (true) {
      const payload = yield take(otpChannel);
      console.log(payload, 'received');
      // const code = payload.split('\n')[0].split(':')[1].trim();
      // yield put(externalEvents.setOTP(code, new Date()));
    }
  }
}

export default watchOTP;
```

With this code, library inconsistently caught up to 3 first sms (most of the time of was one, though), rendering the following output to the console
![image](https://user-images.githubusercontent.com/28301667/71481517-f489f300-281f-11ea-8882-e1cf835f3ba0.png)

Which means, that sometimes new listener was created and sometimes not. I'm not acquainted with java to find whether there's an issue with the retriever api itself or with this library.

Therefore, @Bruno-Furtado is there a way to alter this behavior or does it required to kill & register a new listener for every expected sms (which still doesn't have a consistent behavior)?

**Comment by Bruno-Furtado** [comment]
@NikitaNeganov, 

You can receive more than one message.
Here is an example I tested on the [example app](https://github.com/Bruno-Furtado/react-native-sms-retriever/tree/master/example):
<img width="647" alt="Screen Shot 2019-12-31 at 13 06 51" src="https://user-images.githubusercontent.com/2801580/71626952-8f8f1e00-2bce-11ea-8d47-32f7ce7d4e5d.png">

- - -

In summary:
- Keep the listener working (it means: don't remove it)
- Start the SMS retriever every time you received a new message.

**Comment by NikitaNeganov** [comment]
@Bruno-Furtado nice, it works, thank you!

**Comment by vevnkataSukumar** [comment]
@Bruno-Furtado it didn't work for me. Only. for the first time it is listening but later not. Can u please give solution.

**Comment by vevnkataSukumar** [comment]
check the code Snippet

            const registered = await SmsRetriever.startSmsRetriever();
            console.log("iSregistered: ", registered);
            if (registered) {
                SmsRetriever.addSmsListener(event => {
                    console.log("addSmsListener: ", event);
                    if ((event) && (event.message)) {
                        console.log(event.message);
                    } else {
                        // error event
                        console.log("other than Message: ", event);
                    }
                    SmsRetriever.startSmsRetriever();
                });
            }
