### ISSUE TITLE
4 phone numbers giving on dialog. After clicked on button for fetching sim numbers but on dialog box 4 numbers giving me. 

### ISSUE THREAD

**Issue by patilrahul9923** [Bruno-Furtado/react-native-sms-retriever#26]
### Environment

* React Native Version
* Platform: iOS / Android / Both
* Device: Which One / Simulator
* OS Version
* react-native-sms-retriever version
* Devtools: Xcode Version / Android Studio Version
* Build Tools Version (Android only)

### Description

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or prints if needed.

### Solution

Do you know what needs to be done to address this issue? Ideally, provide a pull request with a fix.

**Comment by Bruno-Furtado** [comment]
@patilrahul9923 please describe the issue considerer the template.

**Comment by patilrahul9923** [comment]
I am using redmi 5 phone. which is in two sim cards only but it will give me 4 mobile numbers.
in this two numbers not mine.
![Screenshot_2020-01-20-16-56-45-074_com google android gms](https://user-images.githubusercontent.com/42463350/73063309-82f7a000-3ec4-11ea-800b-5706f70f83cf.jpg)

**Comment by patilrahul9923** [comment]
And also another problem in sms reading, addSmsListner() is not working.

**Comment by Bruno-Furtado** [comment]
@patilrahul9923 the modal is presented by Google API, not for the module. So, for Google you only have 4 numbers. I suggest you check your Google account. The other question I will answer here: https://github.com/Bruno-Furtado/react-native-sms-retriever/issues/27
