### ISSUE TITLE
Same issue . addSmsListner not working when i get the message.

### ISSUE THREAD

**Issue by patilrahul9923** [Bruno-Furtado/react-native-sms-retriever#27]
### Environment

* React Native Version
* Platform: iOS / Android / Both
* Device: Which One / Simulator
* OS Version
* react-native-sms-retriever version
* Devtools: Xcode Version / Android Studio Version
* Build Tools Version (Android only)

### Description

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or prints if needed.

### Solution

Do you know what needs to be done to address this issue? Ideally, provide a pull request with a fix.

**Comment by Bruno-Furtado** [comment]
@patilrahul9923 please describe the issue considerer the template.

**Comment by patilrahul9923** [comment]
I have written code for otp fetching but I am not able to read sms . After getting the sms addSmsListner() not working.  please give me any solution for read the sms.

**Comment by Bruno-Furtado** [comment]
@patilrahul9923 you can check more details about how to read the SMS content [here](https://github.com/Bruno-Furtado/react-native-sms-retriever/wiki/SMS-Rules).

My suggestion: try to compile the [example](https://github.com/Bruno-Furtado/react-native-sms-retriever/tree/master/example) project of the repo using the same hash described on the [wiki](https://github.com/Bruno-Furtado/react-native-sms-retriever/wiki/SMS-Rules).

**Comment by kesha-antonov** [comment]
Hi
I wrote ruby script to get correct hash for SMS https://github.com/kesha-antonov/android-sms-verification-hash
Maybe it'll help future readers like me
