### ISSUE TITLE
Is <#> really necessary?

### ISSUE THREAD

**Issue by kazzkiq** [Bruno-Furtado/react-native-sms-retriever#29]
Taking a look at the [SMS Retriever API](https://developers.google.com/identity/sms-retriever/verify), it seems there is no need to add the `<#>` code at the start of the message. Only the app hash string is needed.

So instead of sending this SMS:

```
<#> Hello, your code is: 383838
3gh3k3j2k2l
```

You could simply send:

```
Hello, your code is: 383838
3gh3k3j2k2l
```

Which is better for user readability. What do you think?

**Comment by vishdroid** [comment]
Any update on this ?

**Comment by Bruno-Furtado** [comment]
@kazzkiq I saw the documentation and you are right. But I guess we don't need to do nothing on the module. It's just update our documentation, right?

**Comment by rtman** [comment]
@Bruno-Furtado so long as it works without the <#> then just update the documentation i would think?

**Comment by kazzkiq** [comment]
[Some articles](https://medium.com/@wilderpereira/secure-android-otp-account-verification-with-the-sms-retriever-api-c395c1985fbf) say that you can replace `<#>` with `\u200b\u200b` which are invisible to the user. I used those unicode characters in my app and this library worked perfectly with them.

So I guess its just a matter of updating the docs, yes.
