### ISSUE TITLE
i am unable to retrive the message  can you send the working example

### ISSUE THREAD

**Issue by kush11** [Bruno-Furtado/react-native-sms-retriever#3]
_onSmsListenerPressed = async () => {
    try {
      const registered = await SmsRetriever.startSmsRetriever();
      if (registered) {
        SmsRetriever.addSmsListener(event => {
          console.log(event.message);
//I am not able to get the response here event.message
          SmsRetriever.removeSmsListener();
        });
      }
    } catch (error) {

      console.log(JSON.stringify(error));
    }
  };

**Comment by Bruno-Furtado** [comment]
@kush11, the const `registered` is true?

**Comment by raghavendramogeraya** [comment]
Facing same issue. Using React native v0.56 and Android OS 7 and device Redmi Note 4.
Even the example is not working for me. Getting const registered as true. No further logs.
Please help me if any further settings required.

**Comment by Bruno-Furtado** [comment]
@raghavendramogeraya, can you have phone numbers registered on your Google Account?
A good test is install the Lyft app and check if the app display the hint with your phone number on login screen.

**Comment by raghavendramogeraya** [comment]
@Bruno-Furtado No. My number is not registered with Google Account. Is this requirement for this library? I installed Lyft app and it's also not showing the hint with my phone number on sign up screen. 
Please let me know if any permission needs to be added to work this?

**Comment by raghavendramogeraya** [comment]
@Bruno-Furtado Any updates?

**Comment by Bruno-Furtado** [comment]
@raghavendramogeraya, just sharing...

I also noticed that this problem occurred to me when I didn't have a phone number on my Google account. I added a number but the problem has not been fixed. After a few days, I tested again and the number was displayed. So... I believe the Google API has some cache and it takes time to display the your number.

**Comment by nielsdB97** [comment]
@Bruno-Furtado I'm also running into this issue. The listener resolves but when listening for incoming messages, no event is received when receiving an SMS.
I think the author of this issue was facing this same problem where we can't read incoming SMS messages, which is separate from the phonenumber issue #2.

**Comment by patilrahul9923** [comment]
Same issue. addSmsListner not working after getting sms.

**Comment by Bruno-Furtado** [comment]
@nielsdB97 / @patilrahul9923, 

You can try to run the [example](https://github.com/Bruno-Furtado/react-native-sms-retriever/tree/master/example).
[Here](https://github.com/Bruno-Furtado/react-native-sms-retriever/wiki/SMS-Rules) is hash code for example.

Let me know if you have problems.
