### ISSUE TITLE
App crashes on iOS

### ISSUE THREAD

**Issue by hhashem1** [Bruno-Furtado/react-native-sms-retriever#47]
### Environment

* React Native Version 62.2
* Platform: iOS
* Device: Simulator
* OS Version 12
* react-native-sms-retriever version 1.1.1
* Xcode Version 12.3

### Description

The library is working fine on Android. But trying to run it on iOS the app crashes with the following error:

Error: InternalError Metro has encountered an error: While trying to resolve module `react-native-sms-retriever` from file `/Users/*****/src/screens/smsCodeVerification/smsCodeVerificationAndroid.js`, the package `/Users/****/node_modules/react-native-sms-retriever/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/*****/node_modules/react-native-sms-retriever/index.js`. Indeed, none of these files exist:

  * /Users/*****/node_modules/react-native-sms-retriever/index.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/****/node_modules/react-native-sms-retriever/index.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

**Comment by JorgeFPeres** [comment]
**First check this:**

This can happen if you have a custom configuration for metro and haven't specified ts and tsx as valid extensions.
These extensions are present in the default configuration. To check if this is the issue, look for a metro.config.js file in your project and check if you have specified the sourceExts option. It should at least have the following configuration:

sourceExts: ['js', 'json', 'ts', 'tsx'];


**Second**

This happen when you install a new library, while the Metro is runnig, so close your Metro and your Ios simulator, reopen. 

Hope this works. 
See you.

**Comment by hhashem1** [comment]
Thank you for your help. The second solution solved the problem.
