### ISSUE TITLE
Problem attaching contact.

### ISSUE THREAD

**Issue by rutujayewalekar29** [Bruno-Furtado/react-native-sms-retriever#5]
### Environment

* React Native Version: 0.55.4
* Platform: Android
* Device: One plus, Mi and emulator
* OS Version: 6,7,8
* react-native-sms-retriever version : 1.0.1

### Description
 I am using react native-sms-retriever to autofill otp and there is another place in app where I use react-native-contacts-picker to attach a contact. Now when I try to attach the contact I am unable to do so. I get error in PhoneNumberHelper.java line 158. This is because I am not using the service to getPhoneNumber. The problem is in the event listener for phone number. There should be some mechanism to add and remove this event listener.

**Comment by Bruno-Furtado** [comment]
@rutujayewalekar29, thanks for the sugestion.
I'll work on this feature as soon as possible.
Feel free to open a PR as well.

**Comment by Bruno-Furtado** [comment]
@rutujayewalekar29,
The issue was solved in #8 and a new version of the library was generated (1.0.3).

**Comment by rutujayewalekar29** [comment]
@Bruno-Furtado Thanks! This fix solved my issue.
