### ISSUE TITLE
Crash on startup IOS (undefined is not an object (evaluating 'i.requestPhoneNumber')' )

### ISSUE THREAD

**Issue by amrosama2020** [Bruno-Furtado/react-native-sms-retriever#6]
### Environment

* React Native Version 0.49
* Platform: iBoth
* Device: Simulator
* OS Version: IOS 12 
* react-native-sms-retriever 1.0.1
* Devtools: Xcode 12

### Description

I'm not sure if this is a genuine issue or a mistake on my behalf, I have successfully installed and integrated the SMS retriver and tested it on android.
But now I get the following error which crashes the application on launch on IOS (simulator and device):
2019-03-06 15:49:42.386634+0200 EFGConnect[74395:1038144] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'i.requestPhoneNumber')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'i.requestPh..., stack:

I can see that  'i.requestPhoneNumber' is included in ios/main.jsbundle which is causing this error.

### Solution

I think excluding the plugin from IOS linking would fix this issue.

Again sorry if this is not a real issue, I just couldn't find any documentation regarding IOS.

**Comment by Bruno-Furtado** [comment]
Hey @amrosama2020, no worries. That's a good point. Would you open a PR with this fix?

**Comment by Bruno-Furtado** [comment]
@amrosama2020,

The #7 solved your problem. The version 1.0.2 was released today.
Now you will not have problems with import.

**Comment by amrosama2020** [comment]
Thanks a lot Bruno, I can confirm that it is working now on IOS devices.

N.B. I tried a similar fix but yours is much cleaner, thank you.
